// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDatabaseInstance = "database_instance"

// DatabaseInstance mapped from table <database_instance>
type DatabaseInstance struct {
	ID                  int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Hostname            string    `gorm:"column:hostname;not null" json:"hostname"`
	Port                int32     `gorm:"column:port;not null" json:"port"`
	LastChecked         time.Time `gorm:"column:last_checked;not null;default:CURRENT_TIMESTAMP" json:"last_checked"`
	LastSeen            time.Time `gorm:"column:last_seen" json:"last_seen"`
	ServerID            int32     `gorm:"column:server_id;not null" json:"server_id"`
	Version             string    `gorm:"column:version;not null" json:"version"`
	BinlogFormat        string    `gorm:"column:binlog_format;not null" json:"binlog_format"`
	LogBin              int32     `gorm:"column:log_bin;not null" json:"log_bin"`
	LogSlaveUpdates     int32     `gorm:"column:log_slave_updates;not null" json:"log_slave_updates"`
	BinaryLogFile       string    `gorm:"column:binary_log_file;not null" json:"binary_log_file"`
	BinaryLogPos        int64     `gorm:"column:binary_log_pos;not null" json:"binary_log_pos"`
	MasterHost          string    `gorm:"column:master_host;not null" json:"master_host"`
	MasterPort          int32     `gorm:"column:master_port;not null" json:"master_port"`
	SlaveSqlRunning     int32     `gorm:"column:slave_sql_running;not null" json:"slave_sql_running"`
	SlaveIoRunning      int32     `gorm:"column:slave_io_running;not null" json:"slave_io_running"`
	MasterLogFile       string    `gorm:"column:master_log_file;not null" json:"master_log_file"`
	ReadMasterLogPos    int64     `gorm:"column:read_master_log_pos;not null" json:"read_master_log_pos"`
	RelayMasterLogFile  string    `gorm:"column:relay_master_log_file;not null" json:"relay_master_log_file"`
	ExecMasterLogPos    int64     `gorm:"column:exec_master_log_pos;not null" json:"exec_master_log_pos"`
	SecondsBehindMaster int64     `gorm:"column:seconds_behind_master" json:"seconds_behind_master"`
	SlaveLagSeconds     int64     `gorm:"column:slave_lag_seconds" json:"slave_lag_seconds"`
	NumSlaveHosts       int32     `gorm:"column:num_slave_hosts;not null" json:"num_slave_hosts"`
	SlaveHosts          string    `gorm:"column:slave_hosts;not null" json:"slave_hosts"`
	ClusterName         string    `gorm:"column:cluster_name;not null" json:"cluster_name"`
	CreateTime          time.Time `gorm:"column:create_time" json:"create_time"`
	UpdateTime          time.Time `gorm:"column:update_time" json:"update_time"`
}

// TableName DatabaseInstance's table name
func (*DatabaseInstance) TableName() string {
	return TableNameDatabaseInstance
}
